### ISSUE TITLE
ConnectionFlowFactory.java Line#60 should use rootCertificatePassphrase rather than certificateAuthority.getPassPhrase()

### ISSUE THREAD

**Issue by yabin-kang** [linkedin/flashback#12]

**Comment by sf1152** [comment]
I made some changes to get rid of unnecessary keyStore setup. Basically proxy will pre-load JKS at bootstrap and use it for proxy to server interaction. It won't impact client to proxy side interaction because
1. If client and flashback run in the different process, they can use different trust store so we can make sure client to proxy interaction could use user defined certificate and proxy to server could continue use the JKS.
2. If client and flashback run in the same process and after proxy started, client could change whatever user defined trust store to guarantee interaction between client and proxy working properly.
